"""create portfolio holdings

Revision ID: 458304aba1e7
Revises: 2d0dd220a5ef
Create Date: 2026-07-29 15:37:38.355154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458304aba1e7'
down_revision: Union[str, Sequence[str], None] = '2d0dd220a5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_buy_price > 0', name='ck_portfolio_average_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_portfolio_quantity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'display_symbol', name='uq_portfolio_user_symbol')
    )
    op.create_index(op.f('ix_portfolio_holdings_user_id'), 'portfolio_holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_holdings_user_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    # ### end Alembic commands ###
